---
title: "SAKPlot Cheat Sheet"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{SAKPlot Cheat Sheet}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(SAKPlot)
library(datasets)
data(iris)
```


Examples of some plots that can be generated by the `SAKPlot` package. 

```{r fig.height=5, fig.width=9}
par(mfrow = c(1, 2), mar = c(5, 4, 3, 6) + 0.1)
d <- SAKDifference(iris, groups = c("versicolor", "setosa"), data.col = "Sepal.Length", group.col = "Species")
SAKPlot(d, main = "Two groups")
par(mar = c(5, 4, 3, 2) + 0.1)
d <- SAKDifference(iris, data.col = "Sepal.Length", group.col = "Species")
SAKPlot(d, violin = "grey50", violin.fill = "grey90", violin.shape = "left", points = SAKTransparent("black", 0.9), main = "Three groups")
```

```{r fig.height=6, fig.width=9}
par(mfrow = c(1, 2))
d <- SAKDifference(iris, data.col = "Sepal.Length", group.col = "Species")
SAKPlot(d, bar = TRUE, error.bars.type = "SD", points = FALSE, violin = FALSE, main = "Bar chart with std. deviation")
SAKPlot(d, box = TRUE, error.bars.type = "CI", points = FALSE, violin = FALSE, main = "Box plot with 95% CI")
```

```{r fig.height=6, fig.width=9}
par(mfrow = c(1, 2))
d <- SAKDifference(iris, data.col = "Sepal.Length", group.col = "Species", effect.type = "cohens")
SAKPlot(d, main = "Cohen's d")
d <- SAKDifference(iris, data.col = "Sepal.Length", group.col = "Species", effect.type = "hedges", ci.conf = 0.98)
SAKPlot(d, ef.size.violin = FALSE, central.tendency = "blue", violin.trun = FALSE, main = "Hedges' g, 98% CI")
```

```{r fig.height=5, fig.width=7}
par(mar = c(5, 4, 3, 5) + 0.1)
# Add in some fake sex data to the insulin data set
data <- cbind(insulin, Sex = sample(c("Male", "Female"), nrow(insulin), replace = TRUE))
# Thin it the data so individual symbols are visible
data <- data[data$id %in% 1:15, ]

d <- SAKDifference(data, "sugar", "treatment", "id", groups = c("Before insulin" = "before", "After insulin" = "after"), na.rm = TRUE)
SAKPlot(d, 
        left.ylab = "Blood sugar level",
        violin.shape = c("left", "right"), violin.dx = c(-0.055, 0.055), violin.width = 0.3, 
        points = "black",
        pch = ifelse(data$Sex == "Female", 21, 24),
        points.params = list(bg = ifelse(data$Sex == "Female", "red", "blue")), 
        ef.size.pch = 19,
        ef.size.violin = "blue",
        ef.size.violin.shape = "full",
        central.tendency = FALSE,
        main = "Customised plot")
```

```{r fig.height=4, fig.width=7}
par(mar = c(5, 4, 3, 1) + 0.1)
set.seed(1)
data <- data.frame(Measurement = unlist(lapply(c(10, 12, 8, 8.5, 9, 9.1), function(m) rnorm(20, m))),
                   Group = rep(paste0("g", 1:6), each = 20),
                   Id = rep(1:6, 20))
d <- SAKDifference(data, 1, 2, 3, groups = c("Control 1" = "g1", "Treatment 1" = "g2", "Control 2" = "g3", "Treatment 2" = "g4", "Control 3" = "g5", "Treatment 3" = "g6"), 
                   contrasts = "g2 - g1, g4 - g3, g6 - g5")
SAKPlot(d, box = TRUE, group.dx = c(0.2, -0.2), paired = FALSE, points = FALSE, box.pars = list(boxwex = 0.4), ef.size.violin = FALSE, main = "Group offsets")
```

```{r fig.height=5, fig.width=6}
par(mar = c(5, 4, 3, 9) + 0.1)
effectSizes <- c("No effect" = 0, "Large positive effect" = 0.8, "Huge positive effect" = 2)
d <- SAKDifference(damselfly, 1, 3, effect.type = "cohen", groups = c("Juvenile" = "juvenile", "Adult" = "adult"), na.rm = TRUE)
SAKPlot(d, violin.shape = c("left", "right"), violin.dx = c(-0.05, 0.05), violin.width = 0.3, main = "Effect size interpretation, right", ef.size.ticks = effectSizes, ef.size.label = "", ef.size.las = 1)

par(mar = c(5, 9, 3, 1) + 0.1)
SAKPlot(d, box = TRUE, ef.size.ticks = effectSizes, ef.size.position = "below", ef.size.las = 1, main = "Effect size interpretation, below", ef.size.label = "")
```
